package com.highpass.runspot.chat.service;
import com.highpass.runspot.chat.domain.ChatRoomMember;import com.highpass.runspot.chat.exception.*;import com.highpass.runspot.chat.repository.*;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataAccessException;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor
public class ChatReadService {private final ChatRoomMemberRepository members;private final ChatMessageRepository messages;private final StringRedisTemplate redis;
 public void incrementForRecipients(Long roomId,Long senderId){for(ChatRoomMember member:members.findByRoomIdAndLeftAtIsNull(roomId)){if(!member.getUser().getId().equals(senderId)){try{redis.opsForHash().increment(key(member.getUser().getId()),roomId.toString(),1);}catch(DataAccessException ignored){}}}}
 public long unread(Long userId,ChatRoomMember member){String field=member.getRoom().getId().toString();try{Object cached=redis.opsForHash().get(key(userId),field);if(cached!=null)return Long.parseLong(cached.toString());}catch(DataAccessException ignored){}long count=member.getLastReadMessageId()==null?messages.countByRoomId(member.getRoom().getId()):messages.countByRoomIdAndIdGreaterThan(member.getRoom().getId(),member.getLastReadMessageId());try{redis.opsForHash().put(key(userId),field,Long.toString(count));}catch(DataAccessException ignored){}return count;}
 public Map<Long,Long> unreadByRoom(Long userId,List<ChatRoomMember> mine){Map<Long,Long> result=new HashMap<>();Map<Object,Object> cached;try{cached=redis.opsForHash().entries(key(userId));}catch(DataAccessException e){cached=Map.of();}Map<String,String> recovered=new HashMap<>();for(ChatRoomMember member:mine){Long roomId=member.getRoom().getId();Object value=cached.get(roomId.toString());long count;if(value!=null){count=Long.parseLong(value.toString());}else{count=member.getLastReadMessageId()==null?messages.countByRoomId(roomId):messages.countByRoomIdAndIdGreaterThan(roomId,member.getLastReadMessageId());recovered.put(roomId.toString(),Long.toString(count));}result.put(roomId,count);}if(!recovered.isEmpty()){try{redis.opsForHash().putAll(key(userId),recovered);}catch(DataAccessException ignored){}}return result;}
 public long total(Long userId){List<ChatRoomMember> mine=members.findByUserIdAndLeftAtIsNullOrderByRoomLastMessageAtDesc(userId);return unreadByRoom(userId,mine).values().stream().mapToLong(Long::longValue).sum();}
 @Transactional public void read(Long userId,Long roomId,Long messageId){ChatRoomMember member=members.findByRoomIdAndUserIdAndLeftAtIsNull(roomId,userId).orElseThrow(()->new ChatException(ChatErrorCode.NOT_ROOM_MEMBER));if(messages.findById(messageId).filter(m->m.getRoom().getId().equals(roomId)).isEmpty())throw new ChatException(ChatErrorCode.INVALID_CHAT_MESSAGE);member.read(messageId);try{redis.opsForHash().delete(key(userId),roomId.toString());}catch(DataAccessException ignored){}}
 private String key(Long userId){return "chat:unread:"+userId;}}
