package com.highpass.runspot.chat.service;
import com.highpass.runspot.auth.domain.User;import com.highpass.runspot.auth.domain.dao.UserRepository;import com.highpass.runspot.chat.domain.*;import com.highpass.runspot.chat.dto.*;import com.highpass.runspot.chat.exception.*;import com.highpass.runspot.chat.repository.*;import com.highpass.runspot.session.domain.Session;import com.highpass.runspot.session.domain.dao.SessionRepository;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class ChatRoomService {
 private final ChatRoomRepository rooms;private final ChatRoomMemberRepository members;private final ChatMessageRepository messages;private final SessionRepository sessions;private final UserRepository users;private final ChatReadService reads;
 public List<ChatRoomResponse> rooms(Long userId,ChatRoomType type){List<ChatRoomMember> mine=members.findByUserIdAndLeftAtIsNullOrderByRoomLastMessageAtDesc(userId).stream().filter(m->type==null||m.getRoom().getRoomType()==type).toList();Set<Long> ids=mine.stream().map(m->m.getRoom().getLastMessageId()).filter(Objects::nonNull).collect(Collectors.toSet());Map<Long,ChatMessage> last=messages.findAllById(ids).stream().collect(Collectors.toMap(ChatMessage::getId,Function.identity()));Map<Long,Long> unread=reads.unreadByRoom(userId,mine);return mine.stream().map(m->response(m.getRoom(),last.get(m.getRoom().getLastMessageId()),members.findByRoomIdAndLeftAtIsNull(m.getRoom().getId()).size(),unread.getOrDefault(m.getRoom().getId(),0L))).toList();}
 public ChatRoomResponse detail(Long userId,Long roomId){ChatRoomMember mine=member(roomId,userId);ChatRoom r=room(roomId);ChatMessage last=r.getLastMessageId()==null?null:messages.findById(r.getLastMessageId()).orElse(null);return response(r,last,members.findByRoomIdAndLeftAtIsNull(roomId).size(),reads.unread(userId,mine));}
 public ChatMessagePageResponse messages(Long userId,Long roomId,Long cursor,int size){member(roomId,userId);int limit=Math.min(Math.max(size,1),100);List<ChatMessage> found=messages.findPage(roomId,cursor,PageRequest.of(0,limit+1));boolean more=found.size()>limit;List<ChatMessage> page=more?found.subList(0,limit):found;Long next=page.isEmpty()?null:page.get(page.size()-1).getId();return new ChatMessagePageResponse(page.stream().map(ChatMessageResponse::from).toList(),next,more);}
 @Transactional public DirectRoomResponse direct(Long userId,DirectRoomRequest request){Optional<ChatRoom> existing=rooms.findBySessionIdAndGuestIdAndRoomType(request.sessionId(),userId,ChatRoomType.DIRECT);if(existing.isPresent())return new DirectRoomResponse(existing.get().getId(),false);Session session=sessions.findById(request.sessionId()).orElseThrow(()->e(ChatErrorCode.SESSION_NOT_FOUND));if(session.getHostUser().getId().equals(userId))throw e(ChatErrorCode.HOST_DIRECT_ROOM_NOT_ALLOWED);User guest=users.findById(userId).orElseThrow(()->e(ChatErrorCode.USER_NOT_FOUND));try{ChatRoom room=rooms.saveAndFlush(ChatRoom.direct(session,guest));members.saveAll(List.of(ChatRoomMember.join(room,session.getHostUser(),ChatMemberRole.HOST),ChatRoomMember.join(room,guest,ChatMemberRole.MEMBER)));return new DirectRoomResponse(room.getId(),true);}catch(DataIntegrityViolationException ex){ChatRoom room=rooms.findBySessionIdAndGuestIdAndRoomType(request.sessionId(),userId,ChatRoomType.DIRECT).orElseThrow(()->ex);return new DirectRoomResponse(room.getId(),false);}}
 @Transactional public void leave(Long userId,Long roomId){ChatRoomMember m=member(roomId,userId);if(m.getRole()==ChatMemberRole.HOST)throw e(ChatErrorCode.NOT_ROOM_MEMBER);m.leave();}
 @Transactional public void delete(Long userId,Long roomId){ChatRoomMember m=member(roomId,userId);if(m.getRole()!=ChatMemberRole.HOST)throw e(ChatErrorCode.NOT_ROOM_HOST);m.getRoom().delete();}
 private ChatRoomResponse response(ChatRoom r,ChatMessage m,int count,long unread){return new ChatRoomResponse(r.getId(),r.getRoomType(),r.getTitle(),r.getSession().getId(),count,m==null?null:m.getContent(),r.getLastMessageAt(),unread);}
 private ChatRoom room(Long id){ChatRoom r=rooms.findDetail(id).orElseThrow(()->e(ChatErrorCode.CHAT_ROOM_NOT_FOUND));if(r.getStatus()==ChatRoomStatus.DELETED)throw e(ChatErrorCode.CHAT_ROOM_NOT_FOUND);return r;}
 private ChatRoomMember member(Long roomId,Long userId){return members.findByRoomIdAndUserIdAndLeftAtIsNull(roomId,userId).orElseThrow(()->e(ChatErrorCode.NOT_ROOM_MEMBER));}
 private ChatException e(ChatErrorCode code){return new ChatException(code);}
}
